[package]
authors = ["Yudai Hayashi <yudai0913haya@gmail.com>"]
edition = "2018"
name = "pykk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "pykk"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.13.2"

[dependencies]
num-traits = "0.2.14"
