name: Release

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    create-sdist:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Create source distribution
              uses: PyO3/maturin-action@v1
              with:
                command: sdist
                args: >
                    --out dist